version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - db
  parser:
    build: ./parser
    command: python main.py
    ports:
      - 9000:9000
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=market_matcher
      - POSTGRES_PASSWORD=market_matcher
      - POSTGRES_DB=market_matcher_dev
      
volumes:
  postgres_data: