version: '3.7'

services:
  web:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: exit 0
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 30s
  parser:
    build: ./parser
    command: python main.py parse
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
    env_file:
      - ./parser/.env.dev
  db:
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mm_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  postgres_data: