# Generated by Django 4.2.7 on 2023-12-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('code', models.CharField()),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('category', models.CharField()),
                ('category_code', models.CharField()),
                ('price', models.FloatField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_analysis.store')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
